--
-- Script was generated by Devart dbForge Studio for MySQL, Version 8.0.124.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 2/11/2019 11:48:59 AM
-- Server version: 5.6.41-log
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

--
-- Set default database
--
USE resume;

--
-- Drop table `employment_history`
--
DROP TABLE IF EXISTS employment_history;

--
-- Drop table `user_skill`
--
DROP TABLE IF EXISTS user_skill;

--
-- Drop table `skill`
--
DROP TABLE IF EXISTS skill;

--
-- Drop table `user`
--
DROP TABLE IF EXISTS user;

--
-- Drop table `country`
--
DROP TABLE IF EXISTS country;

--
-- Set default database
--
USE resume;

--
-- Create table `country`
--
CREATE TABLE country (
  id INT(11) NOT NULL AUTO_INCREMENT,
  nationality VARCHAR(255) DEFAULT NULL,
  name VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 4,
AVG_ROW_LENGTH = 8192,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

--
-- Create index `UK_nationality_country` on table `country`
--
ALTER TABLE country 
  ADD UNIQUE INDEX UK_nationality_country(name);

--
-- Create table `user`
--
CREATE TABLE user (
  id INT(11) NOT NULL AUTO_INCREMENT,
  firstname VARCHAR(55) DEFAULT NULL,
  lastname VARCHAR(55) DEFAULT NULL,
  email VARCHAR(50) DEFAULT NULL,
  phone VARCHAR(16) DEFAULT NULL,
  profile_description TEXT DEFAULT NULL,
  birth_date DATE DEFAULT NULL,
  birth_place INT(11) DEFAULT NULL,
  nationality INT(11) DEFAULT NULL,
  address VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 9,
AVG_ROW_LENGTH = 2730,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

--
-- Create foreign key
--
ALTER TABLE user 
  ADD CONSTRAINT FK_user_birthplace FOREIGN KEY (birth_place)
    REFERENCES country(id) ON DELETE NO ACTION;

--
-- Create foreign key
--
ALTER TABLE user 
  ADD CONSTRAINT FK_user_nationality FOREIGN KEY (nationality)
    REFERENCES country(id) ON DELETE NO ACTION;

--
-- Create table `skill`
--
CREATE TABLE skill (
  id INT(11) NOT NULL AUTO_INCREMENT,
  name VARCHAR(50) NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 9,
AVG_ROW_LENGTH = 2730,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

--
-- Create table `user_skill`
--
CREATE TABLE user_skill (
  id INT(11) NOT NULL AUTO_INCREMENT,
  user_id INT(11) DEFAULT NULL,
  skill_id INT(11) DEFAULT NULL,
  power INT(2) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 11,
AVG_ROW_LENGTH = 5461,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

--
-- Create foreign key
--
ALTER TABLE user_skill 
  ADD CONSTRAINT FK_user_skill_skill_id FOREIGN KEY (skill_id)
    REFERENCES skill(id) ON DELETE SET NULL ON UPDATE SET NULL;

--
-- Create foreign key
--
ALTER TABLE user_skill 
  ADD CONSTRAINT FK_user_skill_user_id FOREIGN KEY (user_id)
    REFERENCES user(id) ON DELETE SET NULL ON UPDATE SET NULL;

--
-- Create table `employment_history`
--
CREATE TABLE employment_history (
  id INT(11) NOT NULL AUTO_INCREMENT,
  header VARCHAR(255) DEFAULT NULL,
  begin_date DATE DEFAULT NULL,
  end_date DATE DEFAULT NULL,
  job_description VARCHAR(255) DEFAULT NULL,
  user_id INT(11) NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 2,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

--
-- Create index `FK_employment_history_user_id` on table `employment_history`
--
ALTER TABLE employment_history 
  ADD INDEX FK_employment_history_user_id(user_id);

-- 
-- Dumping data for table country
--
INSERT INTO country VALUES
(1, 'Azeri', 'Azerbaijan'),
(2, 'Albanian', 'Albania'),
(3, 'Bahrainan', 'Bahrain');

-- 
-- Dumping data for table user
--
INSERT INTO user VALUES
(1, 'Alim', 'Qasimov', 'alimqasimov@gmail.com', '+999999999', 'SQL Developer', '1993-01-23', 1, 1, 'Izmir 1'),
(3, 'Asif', 'Kamilov', 'asif@gmail.com', '+455676666', 'Mwhasib', '1993-01-23', NULL, NULL, 'Nizami'),
(5, 'Qasim', 'Qabilov', 'asim@gmail.com', '', 'BI Developer', NULL, NULL, NULL, 'Narimanov 75'),
(6, 'Samir', 'Cabbarov', '', '+94555656', 'PHP Developer', NULL, NULL, NULL, 'Samed Vurgun kuc. 55'),
(7, 'Qalib', 'Imanov', '', '', 'PL/SQL  Developer', NULL, NULL, NULL, ''),
(8, 'Kamil', 'Zabitov', 'kamil@gmail.com', '+94554343234', '', '1997-01-12', NULL, NULL, 'Nizami 123');

-- 
-- Dumping data for table skill
--
INSERT INTO skill VALUES
(2, 'SCALA'),
(3, 'SQL'),
(4, 'JAVA'),
(5, 'PHP'),
(6, 'Python'),
(7, 'C++'),
(8, 'C#');

-- 
-- Dumping data for table user_skill
--
INSERT INTO user_skill VALUES
(6, 1, 3, 10),
(9, 1, 2, 10),
(10, 1, 7, 7);

-- 
-- Dumping data for table employment_history
--
INSERT INTO employment_history VALUES
(1, 'Developer', '2019-01-21', '2019-01-22', 'asdfsds', 1);

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;